import { MuiThemeProvider } from "@material-ui/core/styles";
import { createTheme } from "@mui/material";
import { Inter } from "next/font/google";
import Head from "next/head";
import HomePage from "./component/homepage/HomePage";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const theme = createTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MuiThemeProvider theme={theme}>
        <HomePage />
      </MuiThemeProvider>
    </>
  );
}
